services:
  wdotnetsqlv2:
    image: dotnetsqlv3
    container_name: dotnetsqlv2c
    ports:
      - "5164:80"
    environment:
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
  
